spring:
  kafka:
    producer:
      topic-name: ORDER.NEW-PURCHASE
      bootstrap-servers: :9092
  output.ansi.enabled: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders
